version: '3'
services:
  clash-configs:
    image: clash-configs:0.0.1-SNAPSHOT
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8780:8780"
    volumes:
      - ./data:/data
    container_name: clash-configs
    restart: always
    environment:
      JAVA_OPTS: '-Dfile.encoding=UTF-8 -Dserver.port=8780'
    cpus: "1"
    mem_limit: 128M