spring:
  application:
    name: clash-configs
  datasource:
    url: jdbc:h2:file:${user.dir}/data/demo
    username: ${db.username:clash-configs}
    password: ${db.password:password1.}
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
